## 线性代数

## 标量

In [1]:
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x * y, x / y, x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

## 向量

In [2]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

## 矩阵

- [http://zh-v2.d2l.ai/chapter_preliminaries/linear-algebra.html](http://zh-v2.d2l.ai/chapter_preliminaries/linear-algebra.html)

矩阵乘法本质上来说是扭曲一个空间，

- 对称和反对称

$$
A_{ij} = A_{ji} \ \ \ and \ \ \  A_{ij} = -A_{ji}
$$

- 正定

$$
||x||^{2} = x^{T}x \geq 0 \ \  \text{generalizes to} \ \ \  x^{T}Ax \geq 0
$$

- 正交矩阵

所有的行都相互正交，所有行都有单位长度，可以写成$UU^{T}=1$。

- 特征向量和特征值

不被矩阵改变方向的向量：

$$
Ax = \lambda x
$$

矩阵就是对空间的扭曲，但是有一些向量，被这个矩阵作用之后，不会改变。对称矩阵总是可以找到特征向量，但不是每个矩阵都有特征向量。

### 通过指定两个分量m和n来创建一个形状为$m \times n$的矩阵

In [3]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

### 矩阵的转置

In [4]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

### 对称矩阵(symmetric matrix) $A$等于其转置$A = A^{T}$

In [5]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [6]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

## 张量

&emsp;&emsp;就像向量是标量的推广，矩阵是向量的推广一样，我们可以构建具有更多轴的数据结构。

In [7]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

### 给定具有相同形状的任意两个张量，任何按元素二元运算的结果都将是相同形状的张量。

In [8]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

### 两个矩阵的按元素乘法称为哈达玛积（Hadamard product）

In [9]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

将张量乘以或加上一个标量不会改变张量的形状，其中张量的每个元素都将与标量相加或相乘。

In [10]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

### 降维

In [11]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [12]:
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190.))

我们还可以指定张量沿哪一个轴来通过求和降低维度。

In [13]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

指定axis=1将通过汇总所有列的元素降维（轴1）。因此，输入的轴1的维数在输出形状中消失。

In [14]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

沿着行和列对矩阵求和，等价于对矩阵的所有元素进行求和。

In [15]:
A.sum(axis=[0, 1])  # Same as `A.sum()`

tensor(190.)

### 非降维求和

In [16]:
sum_A = A.sum(axis=1, keepdims=True)
A, sum_A

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 6.],
         [22.],
         [38.],
         [54.],
         [70.]]))

In [17]:
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

如果我们想沿某个轴计算A元素的累积总和，比如axis=0（按行计算），我们可以调用cumsum函数。此函数不会沿任何轴降低输入张量的维度。

In [18]:
A.cumsum(axis=0)  # 按行往下累加求和。

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

### 点积

点积是相同位置的按元素乘积的和

In [19]:
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

我们可以通过执行按元素乘法，然后进行求和来表示两个向量的点积。

In [20]:
torch.sum(x * y)

tensor(6.)

### 矩阵-向量积

矩阵向量积$Ax$是一个长度为$m$的列向量，其$i^{th}$元素是点积$a_{i}^{T}x$

In [21]:
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

### 矩阵-矩阵乘法

In [22]:
B = torch.ones(4, 3)
A, B, torch.mm(A, B)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]))

### 范数

$L_{2}$范数是向量元素平方和的平方根:

$$
||x||_{2} = \sqrt{\sum_{i=1}^{n} x_{i}^{2}}
$$

In [23]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

$L_{1}$范数，它表示为向量元素的绝对值之和。

$$
||x||_{1} = \sum_{i=1}^{n} |x_{i}|
$$

In [24]:
torch.abs(u).sum()

tensor(7.)

对于矩阵而言，矩阵的弗罗贝尼乌斯范数(Frobenius norm)满足向量范数的所有性质，是矩阵元素的平方和的平方根：

$$
||X||_{F} = \sqrt{\sum_{i=1}^{m} \sum_{j=1}^{n} x_{ij}^{2}}
$$

等价于把矩阵拉成一个向量，然后对这个向量做范数。

In [25]:
torch.norm(torch.ones((4, 9)))

tensor(6.)