## 重塑数组

In [1]:
import numpy as np
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(a)
print(a.ravel())  # 将二维数组转为一维数组。
print(a.reshape(3, 2))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


## 数组合并

In [2]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([[7, 8, 9],
              [10, 11, 12]])
print(np.hstack([a, b]))
print(np.vstack([a, b]))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## 矩阵运算

In [3]:
a1 = np.array([[4, 5, 6], [1, 2, 3]])
a2 = np.array([[6, 5, 4], [3, 2, 1]])
print(a1 + a2)
print(a1 / a2)
print(a1 % a2)
print(a1 ** 3)

[[10 10 10]
 [ 4  4  4]]
[[0.66666667 1.         1.5       ]
 [0.33333333 1.         3.        ]]
[[4 0 2]
 [1 0 0]]
[[ 64 125 216]
 [  1   8  27]]


## 矩阵相乘

In [4]:
a3 = a2.T
print(a3)

[[6 3]
 [5 2]
 [4 1]]


In [5]:
print(np.dot(a1, a3)) # 矩阵相乘要用np.dot函数。

[[73 28]
 [28 10]]


## 矩阵求逆

In [6]:
a = np.array([[1, 2, 3], [4, 5, 6], [5, 4, 3]])
print(np.linalg.inv(a))

[[ 2.25179981e+15 -1.50119988e+15  7.50599938e+14]
 [-4.50359963e+15  3.00239975e+15 -1.50119988e+15]
 [ 2.25179981e+15 -1.50119988e+15  7.50599938e+14]]


## 特征值与特征向量

In [9]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
eigenValues, eigenVector = np.linalg.eig(a)
print(eigenValues)
print(eigenVector)

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


## SVD奇异值分解

In [10]:
U, sigma, V = np.linalg.svd(a, full_matrices=False)
print(U)
print(sigma)
print(V)

[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
[1.68481034e+01 1.06836951e+00 4.41842475e-16]
[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]


## 矩阵的行列式

In [12]:
value = np.linalg.det(a)
print(value)

0.0


## QR分解

In [13]:
Q, R = np.linalg.qr(a)
print(Q)
print(R)

[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -8.88178420e-16]]


## 求解线性方程组

有如下方程组：

$$
x - 2y + z = 0 \\
2y - 8z -8 = 0 \\
-4x + 5y +9z + 9 = 0
$$

在求解的时候，我们需要将其转化为$Ax + b = 0$的形式。

In [14]:
import numpy as np
A = np.array([
    [1, -2, 1],
    [0, 2, -8],
    [-4, 5, 9]
])
B = np.array([0, -8, 9])
result = np.linalg.solve(A, B)
print("x = {}".format(result[0]))
print("y = {}".format(result[1]))
print("z = {}".format(result[2]))

x = -29.0
y = -16.0
z = -3.0
