## Scipy中的稀疏矩阵运算

### 1. 基础运用

In [1]:
import scipy.sparse as sp

In [2]:
x = sp.eye(5,5) # 5行5列的单位矩阵
x

<5x5 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements (1 diagonals) in DIAgonal format>

In [3]:
x.format

'dia'

In [4]:
x.data # 查看非0元素

array([[1., 1., 1., 1., 1.]])

In [5]:
x.toarray() # 返回数组形式

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
x.sin().toarray() # 支持正弦、余弦运算

array([[0.84147098, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.84147098, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.84147098, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.84147098, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.84147098]])

In [7]:
x.mean() # 平均值

0.2

In [8]:
x.dot([1,2,3,4,5]) # 内积

array([1., 2., 3., 4., 5.])

In [9]:
x.getrow(0).toarray() # 返回第0行

array([[1., 0., 0., 0., 0.]])

In [10]:
x.getcol(0).toarray() # 返回第0列

array([[1.],
       [0.],
       [0.],
       [0.],
       [0.]])

### 2. 稀疏矩阵处理

#### 2.1）查找稀疏矩阵中非0元素的位置与值

In [11]:
x = sp.bsr_matrix([[1,0,0,0,0], [0,1,0,0,1]])
x

<2x5 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements (blocksize = 1x1) in Block Sparse Row format>

In [12]:
x.toarray()

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 1]])

In [13]:
x.nonzero()  # 非0元素的位置 (0,0), (1,1), (1,4)

(array([0, 1, 1], dtype=int32), array([0, 1, 4], dtype=int32))

In [14]:
sp.find(x) # 非0元素位置和值

(array([0, 1, 1], dtype=int32),
 array([0, 1, 4], dtype=int32),
 array([1, 1, 1]))

#### 2.2）最大值与最小值

In [15]:
x = sp.bsr_matrix([[1,0,0,0,0], [0,1,0,0,1]])
x.max()

1

In [16]:
x.min(axis=0).toarray()

array([[0, 0, 0, 0, 0]])

In [17]:
x.min(axis=1).toarray()

array([[0],
       [0]])

#### 2.3）其它运算

In [18]:
x = sp.bsr_matrix([[1,0,0,0,0],[0,1,0,0,1]])

In [19]:
x.toarray()

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 1]])

In [20]:
x.multiply([1,2,3,4,5]).toarray() # 矩阵内积

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 5]])

In [21]:
x.todense()

matrix([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 1]])

In [22]:
y = sp.bsr_matrix([[1],[2],[3],[4],[5]])
x*y.toarray() # 矩阵乘法

array([[1],
       [7]])

In [23]:
x = sp.bsr_matrix([[1,0,0,0,0],[0,1,0,0,1]])
x.toarray()

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 1]])

- 转置

In [24]:
x.transpose().toarray() # 转置

array([[1, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [0, 1]])

- 取符号

In [25]:
sp.bsr_matrix([0.51, 0.49, -0.500001]).sign().toarray() # 取符号

array([[ 1.,  1., -1.]])

- 加法

In [26]:
x = sp.random(3,5,0.5) # 随机矩阵， 第三个参数表示非0元素的密度
x.toarray()

array([[0.36934812, 0.        , 0.28959786, 0.        , 0.        ],
       [0.        , 0.50831464, 0.41698617, 0.        , 0.        ],
       [0.43594142, 0.        , 0.02238747, 0.68907788, 0.97069512]])

In [27]:
y = sp.random(3, 5, 0.3)
y.todense()

matrix([[0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.025713  , 0.29667432],
        [0.59682796, 0.74728054, 0.        , 0.        , 0.        ]])

In [28]:
z = x + y
z.toarray()

array([[0.36934812, 0.        , 0.28959786, 0.        , 0.        ],
       [0.        , 0.50831464, 0.41698617, 0.025713  , 0.29667432],
       [1.03276938, 0.74728054, 0.02238747, 0.68907788, 0.97069512]])

- 平方根

In [29]:
x = sp.random(3, 5, 0.5)
x.toarray()

array([[0.        , 0.        , 0.        , 0.57764511, 0.        ],
       [0.03846491, 0.15867775, 0.95534087, 0.61075743, 0.        ],
       [0.99039144, 0.23078679, 0.4383663 , 0.        , 0.        ]])

In [30]:
x.sqrt().toarray()

array([[0.        , 0.        , 0.        , 0.76002968, 0.        ],
       [0.19612473, 0.39834376, 0.97741541, 0.78150971, 0.        ],
       [0.99518412, 0.48040274, 0.66209237, 0.        , 0.        ]])

- 幂运算

In [31]:
x.power(2).toarray() 

array([[0.        , 0.        , 0.        , 0.33367388, 0.        ],
       [0.00147955, 0.02517863, 0.91267619, 0.37302464, 0.        ],
       [0.9808752 , 0.05326254, 0.19216502, 0.        , 0.        ]])

- 对角线元素

In [32]:
x.diagonal() # 对角线元素

array([0.        , 0.15867775, 0.4383663 ])

- 向下取整

In [33]:
x.floor().toarray()

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

- 向上取整

In [34]:
x.ceil().toarray()

array([[0., 0., 0., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 0., 0.]])

- 四舍五入

In [35]:
x.rint().toarray()

array([[0., 0., 0., 1., 0.],
       [0., 0., 1., 1., 0.],
       [1., 0., 0., 0., 0.]])

- 维数

In [36]:
x.ndim

2

- 维度

In [37]:
x.shape

(3, 5)

- 求和

In [38]:
x.sum()

4.000430611555351

- 横向求和

In [39]:
x.sum(axis=1) 

matrix([[0.57764511],
        [1.76324097],
        [1.65954453]])

- 纵向求和

In [40]:
x.sum(axis=0)

matrix([[1.02885635, 0.38946454, 1.39370718, 1.18840255, 0.        ]])

In [41]:
sp.tril(x, 3).toarray() # 返回下三角稀疏矩阵

array([[0.        , 0.        , 0.        , 0.57764511, 0.        ],
       [0.03846491, 0.15867775, 0.95534087, 0.61075743, 0.        ],
       [0.99039144, 0.23078679, 0.4383663 , 0.        , 0.        ]])

In [42]:
sp.tril(x, 0).toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.03846491, 0.15867775, 0.        , 0.        , 0.        ],
       [0.99039144, 0.23078679, 0.4383663 , 0.        , 0.        ]])

In [43]:
sp.tril(x, -1).toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.03846491, 0.        , 0.        , 0.        , 0.        ],
       [0.99039144, 0.23078679, 0.        , 0.        , 0.        ]])