## tensor.masked_fill

In [1]:
import torch
from torch.autograd import Variable
input_data = Variable(torch.randn(5, 5))
print(input_data)

tensor([[ 2.1696,  1.3518,  0.8043,  0.0617, -0.7065],
        [-0.4329, -0.2052,  1.2070, -0.6884, -0.2943],
        [ 1.3207,  0.0531,  0.3532,  0.5395,  0.2479],
        [ 2.1948,  1.3653,  0.2753, -0.2121, -0.8682],
        [ 1.8707, -0.6943, -0.0350,  0.2811, -0.1305]])


In [2]:
mask = Variable(torch.zeros(5, 5))
print(mask)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [3]:
final_data = input_data.masked_fill(mask == 0, 1e-9)
print(final_data)

tensor([[1.0000e-09, 1.0000e-09, 1.0000e-09, 1.0000e-09, 1.0000e-09],
        [1.0000e-09, 1.0000e-09, 1.0000e-09, 1.0000e-09, 1.0000e-09],
        [1.0000e-09, 1.0000e-09, 1.0000e-09, 1.0000e-09, 1.0000e-09],
        [1.0000e-09, 1.0000e-09, 1.0000e-09, 1.0000e-09, 1.0000e-09],
        [1.0000e-09, 1.0000e-09, 1.0000e-09, 1.0000e-09, 1.0000e-09]])
