&emsp;&emsp;本小结主要是对PyTorch官网教程的翻译。原文链接为：

1. https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html

- PyTorch官网：[https://pytorch.org/](https://pytorch.org/)

## Tensor

&emsp;&emsp;`Tensor`是一种与`arrays`非常相似的数据结构，在`PyTorch`中采用这种数据结构来编码模型的输入输出和网络参数。

In [1]:
import torch
import numpy as np

### 初始化一个Tensor

#### 从列表中进行创建

In [2]:
data = [[1, 2], [3, 4.]]
x_data = torch.tensor(data)
print("x_data格式如下:\n {}".format(x_data))

x_data格式如下:
 tensor([[1., 2.],
        [3., 4.]])


#### 从其它tensor中创建

In [3]:
t = torch.tensor([1, 2, 3, 4.])
t_ones = torch.ones_like(t)
t_rand = torch.rand_like(t)
print("t_ones is {}".format(t_ones))
print("t_rand is {}".format(t_rand))

t_ones is tensor([1., 1., 1., 1.])
t_rand is tensor([0.0151, 0.0892, 0.5934, 0.2087])


#### tensor中的属性

&emsp;&emsp;`tensor`有个`dtype`属性，表示`tensor`里面数据的数据类型。

In [4]:
t = torch.tensor([1, 2, 3, 4.])
print("从list转变过来的元素类型为 : {}".format(x_data.dtype))

np_array = np.array([1., 2, 3, 4])
x_np = torch.from_numpy(np_array)
print("从 Numpy array转变过来的元素类型为 :{}".format(x_np.dtype))

从list转变过来的元素类型为 : torch.float32
从 Numpy array转变过来的元素类型为 :torch.float64


&emsp;&emsp;从上述运行结果可以看到，如果不指定`tensor`中的数据类型的话，`PyTorch`中默认从`NumPy`转化过来的数据类型其实是`float64`的。

&emsp;&emsp;除了数据类型需要注意以外，这里还有一些其它的属性需要注意：

In [5]:
t = torch.tensor([1, 2, 3, 4.])
print("tensor的shape为: {}".format(t.shape))
print("tensor的存储属性为: {}".format(t.device))

tensor的shape为: torch.Size([4])
tensor的存储属性为: cpu


## Tensor与NumPy共享内存

&emsp;&emsp;`Tensors`和`NumPy ndarrys`可以共享同一块内存。如果我们在`PyTorch`中改变`tensor`数据的值的话，那么相对应`NumPy`的数组也会改变。反过来，如果去改变`Numpy`对应的`array`数组的值的话，这个`Tensor`本身也会发生改变。只要这个改变是原地操作的都可以。



In [6]:
t = torch.tensor([1, 2, 3, 4])
n = t.numpy()
print("t : {}".format(t))
print("n : {}".format(n))

t : tensor([1, 2, 3, 4])
n : [1 2 3 4]


&emsp;&emsp;当对其中一个元素进行累加时，另一个元素也会发生变化。

In [7]:
t.add_(1)
print("t : {}".format(t))
print("n : {}".format(n))

t : tensor([2, 3, 4, 5])
n : [2 3 4 5]


## Tensor操作运算符

&emsp;&emsp;`PyTorch`中提供了有超过`100`中`tensor`的运算符，包括转置、索引、切片、数学运算、线性代数、随机采样。

&emsp;&emsp;在如下链接：[https://pytorch.org/docs/stable/torch.html](https://pytorch.org/docs/stable/torch.html)

### 常用Tensors相关运算符

#### is_tensor

In [8]:
t = torch.tensor([1, 2, 3, 4.])
print("t是tensor: {}".format(torch.is_tensor(t)))

t是tensor: True


&emsp;&emsp;对于这个`is_tensor`运算符来说，源码里面就是非常简单的`isinstance`判断的。

```python
def is_tensor(obj):
    r"""Returns True if `obj` is a PyTorch tensor.

    Note that this function is simply doing ``isinstance(obj, Tensor)``.
    Using that ``isinstance`` check is better for typechecking with mypy,
    and more explicit - so it's recommended to use that instead of
    ``is_tensor``.

    Args:
        obj (Object): Object to test
    Example::

        >>> x=torch.tensor([1,2,3])
        >>> torch.is_tensor(x)
        True

    """
    return isinstance(obj, torch.Tensor)
```

#### is_floating_point

&emsp;&emsp;`is_floating_point`操作符，判断是否是浮点类型。

In [9]:
print(torch.is_floating_point(t))

True


#### is_nonzero

如果输入是一个单个元素的话，可以用来判断是否为0。

In [10]:
torch.is_nonzero(torch.tensor([0.]))

False

In [11]:
torch.is_nonzero(torch.tensor([0.5]))

True

#### nonzero

函数原型：

```python
torch.nonzero(input, *, out=None, as_tuple=False)
```

`as_tuple=False`时，输出结果的大小为$(z \times n)$。`as_tuple=False`时，返回的是一个tuple。

In [12]:
torch.nonzero(torch.tensor([1, 1, 1, 0, 1]))

tensor([[0],
        [1],
        [2],
        [4]])

In [13]:
torch.nonzero(torch.tensor([[0.6, 0.0, 0.0, 0.0],
                            [0.0, 0.4, 0.0, 0.0],
                            [0.0, 0.0, 1.2, 0.0],
                            [0.0, 0.0, 0.0, -0.4]]))

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3]])

In [14]:
torch.nonzero(torch.tensor([1, 1, 1, 0, 1]), as_tuple=True)

(tensor([0, 1, 2, 4]),)

In [15]:
torch.nonzero(torch.tensor([[0.6, 0.0, 0.0, 0.0],
                            [0.0, 0.4, 0.0, 0.0],
                            [0.0, 0.0, 1.2, 0.0],
                            [0.0, 0.0, 0.0, -0.4]]), as_tuple=True)

(tensor([0, 1, 2, 3]), tensor([0, 1, 2, 3]))

#### set_default_tensor_type

&emsp;&emsp;设置默认的`tensor`类型。

In [16]:
torch.tensor([1, 2.3]).dtype

torch.float32

In [17]:
torch.set_default_tensor_type(torch.DoubleTensor)

In [18]:
torch.tensor([1, 2.3]).dtype

torch.float64

#### numel

&emsp;&emsp;返回输入`tensor`中元素的总个数。

In [19]:
a = torch.randn(1, 2, 3, 4)
torch.numel(a)

24

### 创建tensor操作符

#### zeros与zeros_like

In [20]:
t = torch.zeros((2,3))
t

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [21]:
torch.zeros_like(t)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

#### arange

&emsp;&emsp;返回一个`1-D`的`tensor`，这个`tensor`的大小为$\left\lceil\frac{\text { end-start }}{\text { step }}\right\rceil$，函数定义如下：

```python
torch.arange(start=0, end, step=1, *, out=None, dtype=None, layout=torch.strided, device=None,
             requires_grad=False) 
```

&emsp;&emsp;但是取不到`end`。

In [22]:
torch.arange(1, 4, 0.5)

tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000])

#### range

&emsp;&emsp;`range`相对于`arange`来说就是能够取到`end`这个元素。

In [23]:
torch.range(1, 4, 0.5)

/var/folders/x9/xgj8n5xd2bb0cv55w7c72bn40000gn/T/ipykernel_26931/3378922890.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1, 4, 0.5)


tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000])

#### linspace

&emsp;&emsp;与`arange`和`range`不同，`linspace`是指定元素的个数:

In [24]:
torch.linspace(2, 3, 7)

tensor([2.0000, 2.1667, 2.3333, 2.5000, 2.6667, 2.8333, 3.0000])

#### eye

&emsp;&emsp;`eye`的函数定义如下:

```python
torch.eye(n, m=None, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
```

&emsp;&emsp;返回一个`2-D`的`tensor`，对角线上的元素是`1`，其它元素为`0`，需要给定的参数是行和列，如果列参数不给定的话，默认是一个方阵。

In [25]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [26]:
torch.eye(2, 3)

tensor([[1., 0., 0.],
        [0., 1., 0.]])

#### full

&emsp;&emsp;创建一个指定元素的`tensor`。

In [27]:
torch.full(size=(1, 2), fill_value=1.3)

tensor([[1.3000, 1.3000]])

## 索引、切片、连接、转变操作符

#### cat

&emsp;&emsp;对给定的`tensor`序列的指定维度进行拼接，所有的`tensor`，除了待拼接的维度外，需要具有相同的`shape`。

In [28]:
t = torch.randn(2, 3)
t

tensor([[ 1.2783, -1.1765, -0.1997],
        [-1.3430,  0.5486,  1.5526]])

In [29]:
torch.cat((t, t), dim=0)

tensor([[ 1.2783, -1.1765, -0.1997],
        [-1.3430,  0.5486,  1.5526],
        [ 1.2783, -1.1765, -0.1997],
        [-1.3430,  0.5486,  1.5526]])

In [30]:
torch.cat((t, t), dim=1)

tensor([[ 1.2783, -1.1765, -0.1997,  1.2783, -1.1765, -0.1997],
        [-1.3430,  0.5486,  1.5526, -1.3430,  0.5486,  1.5526]])

#### stack

&emsp;&emsp;对`tensor`进行拼接，但是会具有新的维度。

In [31]:
torch.stack((t, t), dim=0)

tensor([[[ 1.2783, -1.1765, -0.1997],
         [-1.3430,  0.5486,  1.5526]],

        [[ 1.2783, -1.1765, -0.1997],
         [-1.3430,  0.5486,  1.5526]]])

In [32]:
torch.stack((t, t), dim=0).size()

torch.Size([2, 2, 3])

In [33]:
torch.stack((t, t), dim=1)

tensor([[[ 1.2783, -1.1765, -0.1997],
         [ 1.2783, -1.1765, -0.1997]],

        [[-1.3430,  0.5486,  1.5526],
         [-1.3430,  0.5486,  1.5526]]])

In [34]:
torch.stack((t, t), dim=1).size()

torch.Size([2, 2, 3])

#### chunk

函数原型为：

```python
torch.chunk(input, chunks, dim=0)
```

如果输入的`tensor`在给定的`dim`维度能够被`chunks`整除的话，返回的所有的`chunks`将具备相同的大小。如果不能够被整除，那么最后一个将不具备之前的那些一样的大小。

In [35]:
t = torch.randn(2, 3)
t

tensor([[-1.1992, -0.6293,  1.6096],
        [ 1.6889,  0.4714,  0.3982]])

In [36]:
torch.chunk(t, 2, dim=0)

(tensor([[-1.1992, -0.6293,  1.6096]]), tensor([[1.6889, 0.4714, 0.3982]]))

In [37]:
torch.chunk(t, 2, dim=1)

(tensor([[-1.1992, -0.6293],
         [ 1.6889,  0.4714]]),
 tensor([[1.6096],
         [0.3982]]))

#### gather

函数原型为：

```python
torch.gather(input, dim, index, *, sparse_grad=False, out=None)
```

对于一个给定的`3-D`的`tensor`，输出可以表示为：

```bash
out[i][j][k] = input[index[i][j][k]][j][k]  # if dim == 0
out[i][j][k] = input[i][index[i][j][k]][k]  # if dim == 1
out[i][j][k] = input[i][j][index[i][j][k]]  # if dim == 2
```



In [38]:
t = torch.tensor([[1, 2], [3, 4]])
t

tensor([[1, 2],
        [3, 4]])

In [39]:
torch.gather(t, 0, torch.tensor([[0, 0], [1, 0]]))

tensor([[1, 2],
        [3, 2]])

&emsp;&emsp;解释一下上述的输出结果：给定的`index`是`[[0, 0], [1, 0]]`，`dim=0`，所以对应输出为：
```python
1. out[0][0] = input[index[0][0]][0] = input[0][0] = 1
2. out[0][1] = input[index[0][1]][1] = input[0][1] = 2
3. out[1][0] = input[index[1][0]][0] = input[1][0] = 3
4. out[1][1] = input[index[1][1]][0] = input[0][1] = 2
```

In [40]:
torch.gather(t, 1, torch.tensor([[0, 0], [1, 0]]))

tensor([[1, 1],
        [4, 3]])

&emsp;&emsp;解释一下上述的输出结果：给定的`index`是`[[0, 0], [1, 0]]`，`dim=1`，所以对应输出为：

```python
1. out[0][0] = input[0][index[0][0]] = input[0][0] = 1
2. out[0][1] = input[0][index[0][1]] = input[0][0] = 1
3. out[1][0] = input[1][index[1][0]] = input[1][1] = 4
4. out[1][1] = input[1][index[1][1]] = input[1][0] = 3
```

#### scatter_

函数原型为：

```python
scatter_(dim, index, src, reduce=None) 
```

从src中按照index索引写入到self中，self的更新公式为：


```python
self[index[i][j][k]][j][k] = src[i][j][k]  # if dim == 0
self[i][index[i][j][k]][k] = src[i][j][k]  # if dim == 1
self[i][j][index[i][j][k]] = src[i][j][k]  # if dim == 2
```



In [41]:
src = torch.arange(1, 11).reshape((2, 5))
src

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [42]:
index = torch.tensor([[0, 1, 2, 0]])
index

tensor([[0, 1, 2, 0]])

In [43]:
torch.zeros(3, 4, dtype=src.dtype).scatter_(0, index, src)

tensor([[1, 0, 0, 4],
        [0, 2, 0, 0],
        [0, 0, 3, 0]])

&emsp;&emsp;解释一下上述的输出结果：给定的`index`是`[[0, 1, 2, 0]]`，`dim=0`，所以对应输出为：

```python
self[index[0][0]][0] = self[0][0] = src[0][0] = 1
self[index[0][1]][1] = self[1][1] = src[0][1] = 2
self[index[0][2]][2] = self[2][2] = src[0][2] = 3
self[index[0][3]][3] = self[0][3] = src[0][3] = 4
```

In [44]:
torch.zeros(3, 4, dtype=src.dtype).scatter_(1, index, src)

tensor([[4, 2, 3, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

&emsp;&emsp;解释一下上述的输出结果：给定的`index`是`[[0, 1, 2, 0]]`，`dim=1`，所以对应输出为：

```python
self[0][index[0][0]] = self[0][0] = src[0][0] = 1
self[0][index[0][1]] = self[0][1] = src[0][1] = 2
self[0][index[0][2]] = self[0][2] = src[0][2] = 3
self[0][index[0][3]] = self[0][0] = src[0][3] = 4
```

&emsp;&emsp;`self[0][0]`之所以会为`4`不是`1`，是因为，它之后会被`src[0][3] = 4`覆盖。

#### transpose

对原`tensor`进行维度转化：

```python
torch.transpose(input, dim0, dim1)
```

In [45]:
t = torch.randn(2, 3)
t

tensor([[-0.3123, -1.7891, -0.9699],
        [ 1.5250,  1.2797,  1.0574]])

In [46]:
t.size()

torch.Size([2, 3])

In [47]:
torch.transpose(t, 1, 0)

tensor([[-0.3123,  1.5250],
        [-1.7891,  1.2797],
        [-0.9699,  1.0574]])

#### reshape

函数原型为：

```python
torch.reshape(input, shape)
```

对给定`input`的`tensor`，将其转变为指定的`shape`。

In [48]:
t = torch.arange(4.)
t

tensor([0., 1., 2., 3.])

In [49]:
torch.reshape(t, (2, 2))

tensor([[0., 1.],
        [2., 3.]])

In [50]:
torch.reshape(t, (-1, ))

tensor([0., 1., 2., 3.])

#### squeeze与unsqueeze

函数原型：

```python
torch.squeeze(input, dim=None, *, out=None)
```

返回一个`tensor`，所有为`1`的维度都会被抹除掉。

比如输入的维度为$(A \times 1 \times B \times C \times 1 \times D)$，输出的tensor的维度将会为$(A \times B \times C \times D)$。

unsqueeze则是在指定维度增加一个维度。

In [51]:
t = torch.zeros(2, 1, 2, 1, 2)
t.size()

torch.Size([2, 1, 2, 1, 2])

In [52]:
t1 = torch.squeeze(t)
t1.size()

torch.Size([2, 2, 2])

In [53]:
t2 = torch.squeeze(t, 1)
t2.size()

torch.Size([2, 2, 1, 2])

In [54]:
t3 = torch.unsqueeze(t2, 0)
t3.size()

torch.Size([1, 2, 2, 1, 2])

#### tack

函数原型为：

```python
torch.take(input, index)
```

依据indices索引，返回一个新的tensor，给定的input tensor会被视为一维的tensor，然后再进行索引。最终返回的结果大小与indices的大小一致。

In [55]:
src = torch.tensor([[4, 3, 5],
                    [6, 7, 8]])
torch.take(src, torch.tensor([0, 2, 5]))

tensor([4, 5, 8])

#### tile

函数原型为：

```python
torch.tile(input, dims)
```

在指定的dims上，复制这个输入的input。如果dims的维度比输入input的维度小，那么会在dims的维度前面填充1。比如输入的input维度为(8, 6, 4, 2)，dims的维度为(2, 2)的话，dims的维度会被填充为(1, 1, 2, 2)。

In [56]:
t = torch.tensor([[1, 2], [3, 4]])
t1 = torch.tile(t, dims=(2,))
t1

tensor([[1, 2, 1, 2],
        [3, 4, 3, 4]])

上述的输出结果就是默认前面的那个维度为1得到的。

In [57]:
t2 = torch.tile(t, dims=(2, 2))
t2

tensor([[1, 2, 1, 2],
        [3, 4, 3, 4],
        [1, 2, 1, 2],
        [3, 4, 3, 4]])

#### unbind

函数原型为：

```python
torch.unbind(input, dim=0) → seq
```

按照dim的指定维度，移除掉一个维度，使其能够变成一个seq。

In [58]:
torch.unbind(torch.tensor([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]]), dim=0)

(tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([7, 8, 9]))

#### where

函数原型为：

```python
torch.where(condition, x, y) 
```

依据给定的`condition`，选择`x`或者`y`。上述操作可以被定义为：

$$
\text { out }_{i}= \begin{cases}\mathrm{x}_{i} & \text { if condition }_{i} \\ \mathrm{y}_{i} & \text { otherwise }\end{cases}
$$



In [59]:
x = torch.randn(3, 2)
y = torch.ones(3, 2)
x

tensor([[ 0.9033, -0.9423],
        [ 0.2850, -0.9643],
        [-1.5870, -0.4876]])

In [60]:
torch.where(x > 0, x, y)

tensor([[0.9033, 1.0000],
        [0.2850, 1.0000],
        [1.0000, 1.0000]])

上述结果中，将`x`元素中大于`0`的值都不变，小于`0`的值都赋值为`1`。

### 随机采样

#### manual_seed

设置随机种子，可以看到其内部是通过调用cuda的设置随机种子来设置的。

```python
def manual_seed(seed) -> torch._C.Generator:
    r"""Sets the seed for generating random numbers. Returns a
    `torch.Generator` object.

    Args:
        seed (int): The desired seed. Value must be within the inclusive range
            `[-0x8000_0000_0000_0000, 0xffff_ffff_ffff_ffff]`. Otherwise, a RuntimeError
            is raised. Negative inputs are remapped to positive values with the formula
            `0xffff_ffff_ffff_ffff + seed`.
    """
    seed = int(seed)
    import torch.cuda

    if not torch.cuda._is_in_bad_fork():
        torch.cuda.manual_seed_all(seed)

    return default_generator.manual_seed(seed)
```

#### bernoulli


函数原型为：

```python
torch.bernoulli(input, *, generator=None, out=None)
```

直接依据概率选择0或者1。

In [61]:
t = torch.empty(3, 3).uniform_(0, 1)
t

tensor([[0.2132, 0.1981, 0.4533],
        [0.3551, 0.9903, 0.0623],
        [0.0401, 0.2300, 0.7234]])

In [62]:
torch.bernoulli(t)

tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [63]:
t1 = torch.ones(3, 3)
torch.bernoulli(t1)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [64]:
t2 = torch.zeros(3, 3)
torch.bernoulli(t2)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

#### normal

生成高斯分布。

函数原型为：

```python
torch.normal(mean, std, *, generator=None, out=None)
```

依据给定的`mean`和`std`，生成随机数。

In [65]:
torch.normal(mean=torch.arange(1., 11.), std=torch.arange(1, 0, -0.1))

tensor([-0.5042,  3.8942,  1.0071,  4.1209,  3.5986,  5.9754,  6.6091,  7.7459,
         8.8295, 10.0138])

如果mean只给定一个标量的话，那么会将这个标量与多个方差共享。

In [66]:
torch.normal(mean=0.0, std=torch.arange(1., 6.))

tensor([-1.2062,  3.6133, -2.6371, -1.1055,  5.0636])

如果没有给定方差的话，方差也会按照默认值1，共享。

In [67]:
torch.normal(mean=torch.arange(1, 6.))

tensor([-0.3958,  2.0300,  4.3742,  3.3280,  4.5535])

还可以指定均值和方差，以及需要生成的数据的大小。

In [68]:
torch.normal(2, 3, size=(2, 4))

tensor([[ 0.9359,  4.5304,  4.3686,  0.1311],
        [ 0.3274,  2.8057, -0.2907,  1.2547]])

#### rand

从[0, 1)的区间里生成一个均匀分布。函数原型为：

```python
torch.rand(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
```

In [69]:
torch.rand(2, 3)

tensor([[0.3630, 0.8106, 0.5972],
        [0.9917, 0.9647, 0.0874]])

#### randn

从均值为`0`，方差为`1`的正太分布中返回数据。函数原型为：

```python
torch.randn(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
```

In [70]:
torch.randn(2, 3)

tensor([[-0.6924,  0.5837, -1.4388],
        [ 0.7302, -0.7548,  1.2483]])

#### randint

函数原型为：

```python
torch.randint(low=0, high, size, \*, generator=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
```

从整数low(包含)到high(不包含)范围内，选取大小为size大小的整数数据出来。

In [71]:
torch.randint(3, 5, (2, 3))

tensor([[3, 3, 3],
        [4, 3, 3]])

#### randperm

函数原型为：

```python
torch.randperm(n, *, generator=None, out=None, dtype=torch.int64, layout=torch.strided, device=None, requires_grad=False, pin_memory=False)
```

返回一个从`0～n-1`的随机整数。

可以在构建数据集的时候用到，用它来产生随机的`index`。

In [72]:
torch.randperm(4)

tensor([0, 1, 2, 3])